# Generated by Django 5.0.2 on 2024-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TourismApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000, verbose_name="title")),
                ("description", models.TextField()),
                ("included_services", models.TextField()),
                ("itinerary", models.TextField()),
                ("travel_mode", models.CharField(max_length=400)),
                ("contact_num", models.CharField(max_length=40)),
                ("locations", models.ManyToManyField(to="TourismApp.location")),
            ],
        ),
    ]
