# Generated by Django 5.0.2 on 2024-02-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TourismApp", "0002_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationimage",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="TourismApp.location",
            ),
        ),
    ]
