# Generated by Django 5.0.2 on 2024-02-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TourismApp", "0003_alter_locationimage_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(
                default="none", upload_to="location_images", verbose_name="Image"
            ),
        ),
        migrations.DeleteModel(
            name="LocationImage",
        ),
    ]
