# Generated by Django 5.0.2 on 2024-02-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TourismApp", "0004_location_image_delete_locationimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="start_city",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="start City"
            ),
        ),
    ]
