# Generated by Django 4.2.3 on 2024-02-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0002_alter_myuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="role",
            field=models.CharField(default="user", max_length=40, verbose_name="Role"),
        ),
    ]
